---
- name: Remove old Jenkins
  apt:
    name: jenkins
    state: absent
    purge: yes
  ignore_errors: yes

- name: Remove old Jenkins keys and sources
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/keyrings/jenkins-keyring.gpg
    - /etc/apt/sources.list.d/jenkins.list

- name: Add Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.gpg
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/
    filename: jenkins
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is running
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Wait for Jenkins to start
  wait_for:
    port: 8080
    delay: 5
    timeout: 60

